---
- name: create static ip
  template:
    src: etc/network/interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644
  when: has_static_ip
  notify: Reboot network
  tags:
    - network