---
- name: create static ip
  template:
    src: etc/network/interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644
  notify: Reboot network
  when: not static_ip_dryrun
  tags:
    - network